version: '3'
services:
#mssql docker
  mybooks-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - mybooksnet

  mybooks-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:myBooks=Server=mybooks-sql,1433;Database=160112;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 27322:80 
    networks:
      - mybooksnet
    links:
      - mybooks-sql
    depends_on:
      - mybooks-sql

networks:
  mybooksnet:
    driver: bridge